require("lead-asteroid-updates")
require("lead-recipe-updates")
require("lead-matter")
require("omni")
require("map-gen-preset-updates")
require("strange-matter")
require("compatibility/248k")
require("compatibility/sciencecosttweakerm")
require("compatibility/crafting-efficiency")

local util = require("data-util")
util.redo_recycling()
